
set(CEPH_PACKAGE_VERSION 0.9)
set(CEPH_REPO_URL https://github.com/ceph/ceph.git)
#set(CEPH_REPO_TAG emperor)
set(CEPH_USER_URL https://github.com/eile/ceph.git)
set(CEPH_AUTOCONF ON)
set(CEPH_DEPENDS )
set(CEPH_DEB_DEPENDS libudev-dev)
set(CEPH_PORT_DEPENDS )
set(CEPH_FORCE_BUILD ${CI_BUILD})
