
set(CLOUDCOMPARE_PACKAGE_VERSION 2.5)
set(CLOUDCOMPARE_REPO_URL https://github.com/eile/trunk)
set(CLOUDCOMPARE_DEPENDS )
set(CLOUDCOMPARE_DEB_DEPENDS )
set(CLOUDCOMPARE_PORT_DEPENDS )
set(CLOUDCOMPARE_FORCE_BUILD ${CI_BUILD})
