
set(OPENMESH_PACKAGE_VERSION 3.1)
set(OPENMESH_REPO_URL https://github.com/eile/OpenMesh2.git)
set(OPENMESH_DEPENDS )
set(OPENMESH_DEB_DEPENDS )
set(OPENMESH_PORT_DEPENDS )
set(OPENMESH_FORCE_BUILD ${CI_BUILD})
